### PR TITLE
Cnpg operator renamechart

### PR DESCRIPTION
**Pull request by wibed**
cloudnative-pg is too long for a name including a dash in its most basic form.
making any extension cumbersome and hard to look at.

cnpg for short seems fine to me. 

it allows for charts like cnpg-db and cnpg-operator to live side by side within the same "namespace" without polluting the naming scheme with confusing additional inecessary dashes.
as to be found within:
- cloudnative-pg-operator
- cloudnative-pg-db

### CODE REVIEW

**Comment by bjw-s** [comment]
Not sure what it is you are trying to do here, but either it is a mistake, or you are missing a useful PR description...

**Comment by wibed** [comment]
> Not sure what it is you are trying to do here, but either it is a mistake, or you are missing a useful PR description...

please it felt obvious to me. thanks for the clarification

**Comment by onedr0p** [comment]
Personally I think the naming is fine as it is.

However, If you really wanted to make this change this isn't how you would go about it. 
You would need to [deprecate the existing chart](https://github.com/helm/charts/blob/master/PROCESSES.md), not rename it. Once that happens and it's released then you can create a PR to add a new chart with the updated name.

**Comment by phisco** [comment]
+1 to what the other said above.

As a general rule of thumb, I would suggest first opening an issue to discuss things like this in the future.

**Comment by wibed** [comment]
> +1 to what the other said above.
> 
> As a general rule of thumb, I would suggest first opening an issue to discuss things like this in the future.

Definitively! if there are any suggestion please feel free to suggest them.

**Comment by wibed** [comment]
what is the state of this pr?

**Comment by itay-grudev** [comment]
If anyone is seriously considering a rename, go with simply `operator` so that the important charts in the repository would be:

* `cnpg/operator`  
* `cnpg/cluster`

That being said there is really no practical need for a rename and that would only cause issues for existing users.

**Comment by wibed** [comment]
> If anyone is seriously considering a rename, go with simply `operator` so that the important charts in the repository would be:
> 
> * `cnpg/operator`
> * `cnpg/cluster`
> 
> **That being said there is really no practical need for a rename and that would only cause issues for existing users.**

i disagree. keeping cnpg in the name distinguishes instances between each other.
it is very inconvenient to go search for identifying bits of information when the name is only "operator"

this pr is ground enough to discuss. everyone can post his opinion

**Comment by onedr0p** [comment]
> this pr is ground enough to discuss. everyone can post his opinion

I disagree, major changes like should be discussed in a Github issue and agreed upon by the cnpg maintainers before work is started on them.

**Pull request closed without merging**
