### PR TITLE
Fix ArgoCD diff on postgresql keys

### PR DESCRIPTION
**Pull request by bozorgmehr96**
Use `with` for every key in the cluster's `spec.postgresql` to prevent generating empty keys.

Fixes: #426

### CODE REVIEW

**Comment by bozorgmehr96** [comment]
If there are other problems like this, give me the key names, and I will fix them.

**Comment by pschichtel** [comment]
@bozorgmehr96 this is my ignoreDifferences rule:

```yaml
group: postgresql.cnpg.io
kind: Cluster
jsonPointers:
- /spec/bootstrap/initdb/postInitApplicationSQL
- /spec/managed
- /spec/postgresql/shared_preload_libraries
- /spec/priorityClassName
- /spec/postgresql/pg_hba
- /spec/postgresql/pg_ident
```

You covered the last two for me

**Comment by bozorgmehr96** [comment]
@pschichtel Thanks. I wrapped them in if blocks.

**Comment by pschichtel** [comment]
@bozorgmehr96 one more: https://github.com/cloudnative-pg/charts/blob/fb45e4ff16ca653f9d26889084f46e36cfa2d550/charts/cluster/templates/scheduled-backups.yaml#L13

**Comment by bozorgmehr96** [comment]
@pschichtel, can you provide a repro? It has a non-empty default value, so it shouldn't have the problem I'm trying to fix here.

**Comment by pschichtel** [comment]
@bozorgmehr96 I customized the schedule, so I don't get the defaults since it's an array. According to https://github.com/cloudnative-pg/charts/blob/fb45e4ff16ca653f9d26889084f46e36cfa2d550/charts/cloudnative-pg/templates/crds/crds.yaml#L15655 and https://github.com/cloudnative-pg/charts/blob/fb45e4ff16ca653f9d26889084f46e36cfa2d550/charts/cloudnative-pg/templates/crds/crds.yaml#L15575 the method field is not required

**Comment by Stevenpc3** [comment]
I am getting a few items in argocd that are oddly just missing on the live manifest.  Not sure if it's the CRD/operator or something with values that might be false by default removed or if these values don't exist anymore?

{63806B04-DB46-4FBC-A9BF-0B554DCE9E79}

* bypassrls
* createrole
* replication
* superuser

There might be more since we didn't set them all.

**Review by itay-grudev — APPROVED** [review]

**Pull request merged**
