### PR TITLE
add containerSecurityContext to Values file

### PR DESCRIPTION
**Pull request by itmwiw**
Set the securityContext at the container level in values file. To install the operator on openshift with the 'restricted' scc, you need to choose a user and an fsgroup allowed by the namespace. User 10001 will give an error.

### CODE REVIEW

**Comment by phisco** [comment]
Hi @itmwiw, thanks for your contribution! Could you enable maintainers' editing on this PR, see [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests), or generate documentation and schema by running `make docs schema` yourself?

**Comment by itmwiw** [comment]
Hello, 
You're welcome. By the way, keep up the good work, this operator is amazing!
I did not found the checkbox to enable maintainer's editing but I did run make docs schema.

**Comment by phisco** [comment]
Awesome, thanks! We'll cut a release of the helm chart as soon as possible!

**Comment by rishinair11** [comment]
Somehow this is not working in OCP 4.14. 
I get this error when installing the Helm chart: 
```
  - lastTransitionTime: "2024-01-12T12:28:45Z"
    lastUpdateTime: "2024-01-12T12:28:45Z"
    message: 'pods "cnpg-cloudnative-pg-7b4546c987-" is forbidden: unable to validate
      against any security context constraint: [provider "anyuid": Forbidden: not
      usable by user or serviceaccount, provider restricted-v2: .containers[0].runAsUser:
      Invalid value: 10001: must be in the ranges: [1000850000, 1000859999], provider
      "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2":
      Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden:
      not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden:
      not usable by user or serviceaccount, provider "machine-api-termination-handler":
      Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2":
      Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden:
      not usable by user or serviceaccount, provider "cassandra-scc": Forbidden: not
      usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable
      by user or serviceaccount, provider "node-exporter": Forbidden: not usable by
      user or serviceaccount, provider "privileged": Forbidden: not usable by user
      or serviceaccount]'
```
I tried creating an SCC as well for the serviceaccount but still not working.

**Pull request merged**
