### PR TITLE
Add support for the `method` parameter in `scheduledBackups`

### LINKED ISSUE #264: Add support for the `method` parameter in `scheduledBackups`
Currently it is not possible to define a scheduled backup with a non-default `method` (like `volumeSnapshot`). I'll create a PR for this.

### PR DESCRIPTION
**Pull request by gpothier**
Fixes #264

### CODE REVIEW

**Review by itay-grudev — CHANGES_REQUESTED** [review]
Could you please:
1. Add a method to the example in the `values.yaml`
2. `make schema docs`

**Comment by gpothier** [comment]
Done, sorry I didn't include it in the first commit.

**Comment by gpothier** [comment]
I just realized I also need to be able to recover from snapshots, I'll add that to the PR.

**Comment by gpothier** [comment]
Nevermind, it is totally possible to restore from a snapshot using the `backup` method.

**Review by itay-grudev — APPROVED** [review]

**Pull request merged**
